services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:24-bookworm
    volumes:
      - ..:/workspace:cached
    ports:
      - "5173:5173"
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - default

networks:
  default:
    name: shoppinglist-network
